[project]
name = "ApplicationTracker"
version = "0.1.0"
description = "A simple discord bot to help track job applications."
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "discord>=2.3.2",
    "dotenv>=0.9.9",
    "pytest>=8.4.2",
]
